// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJYzZp2Hl9Bw5VF0JMc_3uRRat946znGY',
    appId: '1:963946020869:web:7a1287213d2a447ac59c6c',
    messagingSenderId: '963946020869',
    projectId: 'lifetwin-hazem-2004-aba31',
    authDomain: 'lifetwin-hazem-2004-aba31.firebaseapp.com',
    storageBucket: 'lifetwin-hazem-2004-aba31.firebasestorage.app',
    measurementId: 'G-ES4347NJC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdbmPiGjiWuhDLxQwTb1XYZZHF2fNbgf0',
    appId: '1:963946020869:android:6d1bba89b780df9ac59c6c',
    messagingSenderId: '963946020869',
    projectId: 'lifetwin-hazem-2004-aba31',
    storageBucket: 'lifetwin-hazem-2004-aba31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCW6WsSUGFDbToqaQtIdK-4N3Rf9yMbXc',
    appId: '1:963946020869:ios:0ebe166b48ea8af2c59c6c',
    messagingSenderId: '963946020869',
    projectId: 'lifetwin-hazem-2004-aba31',
    storageBucket: 'lifetwin-hazem-2004-aba31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCW6WsSUGFDbToqaQtIdK-4N3Rf9yMbXc',
    appId: '1:963946020869:ios:0ebe166b48ea8af2c59c6c',
    messagingSenderId: '963946020869',
    projectId: 'lifetwin-hazem-2004-aba31',
    storageBucket: 'lifetwin-hazem-2004-aba31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJYzZp2Hl9Bw5VF0JMc_3uRRat946znGY',
    appId: '1:963946020869:web:e7409aa39f4cb824c59c6c',
    messagingSenderId: '963946020869',
    projectId: 'lifetwin-hazem-2004-aba31',
    authDomain: 'lifetwin-hazem-2004-aba31.firebaseapp.com',
    storageBucket: 'lifetwin-hazem-2004-aba31.firebasestorage.app',
    measurementId: 'G-J9BYK0XEGN',
  );
}
